mu Decision : Type 0 :=
  | release : Decision
  | refund : Decision
  | hold : Decision
mu Ballots : Type 0 :=
  | bnil : Ballots
  | bcons (h : Decision) (t : Ballots) : Ballots
def rec foldBallots : (0 B : Type 0) -> (Decision -> B -> B) -> B -> Ballots -> B :=
  fun (0 B : Type 0) (f : Decision -> B -> B) (z : B) (xs : Ballots) =>
    match xs as w in Ballots return B with
    | bnil => z
    | bcons h t => f h (foldBallots B f z t)
def T3 : Type 0 := prod (Nat, prod (Nat, Nat))
mu EqT3 : (0 a : T3) -> (0 b : T3) -> Type 0 :=
  | reflT3 : (0 x : T3) -> EqT3 x x
def bump : Decision -> T3 -> T3 := fun (d : Decision) (t : T3) =>
  match d as w in Decision return T3 with
  | release => tuple (natAdd t.0 1, t.1)
  | refund => tuple (t.0, tuple (natAdd t.1.0 1, t.1.1))
  | hold => tuple (t.0, tuple (t.1.0, natAdd t.1.1 1))
def tallyOf : Ballots -> T3 := foldBallots T3 bump (tuple (0, tuple (0, 0)))
def b0 : Ballots := bnil
def b1 : Ballots := bcons release b0
def b2 : Ballots := bcons refund b1
def b3 : Ballots := bcons hold b2
def b4 : Ballots := bcons release b3
def b5 : Ballots := bcons refund b4
def b6 : Ballots := bcons hold b5
def b7 : Ballots := bcons release b6
def b8 : Ballots := bcons refund b7
def b9 : Ballots := bcons hold b8
def b10 : Ballots := bcons release b9
def b11 : Ballots := bcons refund b10
def b12 : Ballots := bcons hold b11
def b13 : Ballots := bcons release b12
def b14 : Ballots := bcons refund b13
def b15 : Ballots := bcons hold b14
def b16 : Ballots := bcons release b15
def b17 : Ballots := bcons refund b16
def b18 : Ballots := bcons hold b17
def b19 : Ballots := bcons release b18
def b20 : Ballots := bcons refund b19
def b21 : Ballots := bcons hold b20
def b22 : Ballots := bcons release b21
def b23 : Ballots := bcons refund b22
def b24 : Ballots := bcons hold b23
def b25 : Ballots := bcons release b24
def b26 : Ballots := bcons refund b25
def b27 : Ballots := bcons hold b26
def b28 : Ballots := bcons release b27
def b29 : Ballots := bcons refund b28
def b30 : Ballots := bcons hold b29
def b31 : Ballots := bcons release b30
def b32 : Ballots := bcons refund b31
def b33 : Ballots := bcons hold b32
def b34 : Ballots := bcons release b33
def b35 : Ballots := bcons refund b34
def b36 : Ballots := bcons hold b35
def b37 : Ballots := bcons release b36
def b38 : Ballots := bcons refund b37
def b39 : Ballots := bcons hold b38
def b40 : Ballots := bcons release b39
def b41 : Ballots := bcons refund b40
def b42 : Ballots := bcons hold b41
def b43 : Ballots := bcons release b42
def b44 : Ballots := bcons refund b43
def b45 : Ballots := bcons hold b44
def b46 : Ballots := bcons release b45
def b47 : Ballots := bcons refund b46
def b48 : Ballots := bcons hold b47
def b49 : Ballots := bcons release b48
def b50 : Ballots := bcons refund b49
def b51 : Ballots := bcons hold b50
def b52 : Ballots := bcons release b51
def b53 : Ballots := bcons refund b52
def b54 : Ballots := bcons hold b53
def b55 : Ballots := bcons release b54
def b56 : Ballots := bcons refund b55
def b57 : Ballots := bcons hold b56
def b58 : Ballots := bcons release b57
def b59 : Ballots := bcons refund b58
def b60 : Ballots := bcons hold b59
def b61 : Ballots := bcons release b60
def b62 : Ballots := bcons refund b61
def b63 : Ballots := bcons hold b62
def b64 : Ballots := bcons release b63
def b65 : Ballots := bcons refund b64
def b66 : Ballots := bcons hold b65
def b67 : Ballots := bcons release b66
def b68 : Ballots := bcons refund b67
def b69 : Ballots := bcons hold b68
def b70 : Ballots := bcons release b69
def b71 : Ballots := bcons refund b70
def b72 : Ballots := bcons hold b71
def b73 : Ballots := bcons release b72
def b74 : Ballots := bcons refund b73
def b75 : Ballots := bcons hold b74
def b76 : Ballots := bcons release b75
def b77 : Ballots := bcons refund b76
def b78 : Ballots := bcons hold b77
def b79 : Ballots := bcons release b78
def b80 : Ballots := bcons refund b79
def b81 : Ballots := bcons hold b80
def b82 : Ballots := bcons release b81
def b83 : Ballots := bcons refund b82
def b84 : Ballots := bcons hold b83
def b85 : Ballots := bcons release b84
def b86 : Ballots := bcons refund b85
def b87 : Ballots := bcons hold b86
def b88 : Ballots := bcons release b87
def b89 : Ballots := bcons refund b88
def b90 : Ballots := bcons hold b89
def b91 : Ballots := bcons release b90
def b92 : Ballots := bcons refund b91
def b93 : Ballots := bcons hold b92
def b94 : Ballots := bcons release b93
def b95 : Ballots := bcons refund b94
def b96 : Ballots := bcons hold b95
def b97 : Ballots := bcons release b96
def b98 : Ballots := bcons refund b97
def b99 : Ballots := bcons hold b98
def b100 : Ballots := bcons release b99
def tally100 : EqT3 (tallyOf b100) (tuple (34, tuple (33, 33))) := reflT3 (tuple (34, tuple (33, 33)))
